BOARD_SIZE = 8
SQUARES_NUM = 64
INITIAL_NUM_PIECES = 12
WHITE = 1
BLACK = 0
WHITE_NATURAL_DIRECTIONS = [(1, 1), (-1, 1)]
BLACK_NATURAL_DIRECTIONS = [(1, -1), (-1, -1)]

WHITE_SYMBOL = ' W '
BLACK_SYMBOL = ' B '
BLACK_VICTORY = "second"
WHITE_VICTORY = "first"
TIE_GAME = 'tie'
INCOMPLETE_GAME = 'incomplete game'
ILLEGAL_MESSAGE_ONE = 'line'
ILLEGAL_MESSAGE_TWO = 'illegal move:'
EMPTY = ' _ '
